### ISSUE TITLE
Presentation & Replay link is not working

### ISSUE THREAD

**Issue by rvrrpk** [SAP-samples/teched2024-AD180#4]
Kindly provide presentation slides in the git.

**Comment by CarineTD** [comment]
Hi!
Sorry for the inconvenience. The link has been fixed.
[https://github.com/SAP-samples/teched2024-AD180/blob/main/exercises/images/AD180@SAPTechEd2024.pdf](https://github.com/SAP-samples/teched2024-AD180/blob/main/exercises/images/AD180@SAPTechEd2024.pdf)
Kind regards,
Carine
