### ISSUE TITLE
Url not working

### ISSUE THREAD

**Issue by rvrrpk** [SAP-samples/teched2024-AD180#5]
https://github.com/SAP-samples/teched2024-AD180/blob/main/exercises/images/AD180v@SAP_TechEd_2024.pdf
404 - page not found

**Comment by CarineTD** [comment]
Hi!
Sorry for the inconvenience. The link has been fixed.
[https://github.com/SAP-samples/teched2024-AD180/blob/main/exercises/images/AD180@SAPTechEd2024.pdf](https://github.com/SAP-samples/teched2024-AD180/blob/main/exercises/images/AD180@SAPTechEd2024.pdf)
Kind regards,
Carine
